stickies/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns # make static files work with gunicorn

urlpatterns = [
    path('', include('startapp.urls')),
    path('wall/', include('wall.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns() # make static files work with gunicorn

#test with media files
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from django.conf import settings

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

wall/urls.py
from django.urls import path

from . import views

app_name= "wall"

urlpatterns = [
        path('<str:roomName>/', views.room, name='index'),
        path('<str:roomName>/error/<str:errorType>/', views.error, name='error'),
        path('<str:roomName>/addChangePassword/', views.addChangePassword.as_view(), name='addChangePassword'),
        path('<str:roomName>/removePassword/', views.removePassword.as_view(), name='removePassword'),
        path('<str:roomName>/checkUpdate/', views.checkUpdate, name='checkUpdate'),
        path('<str:roomName>/update/', views.update, name='update'),
        path('<str:roomName>/delete/', views.delete.as_view(), name='delete'),
        path('<str:roomName>/moderatorLogin/', views.moderatorLogin.as_view(), name='moderatorLogin'),
        path('<str:roomName>/moderatorLogout/', views.moderatorLogout, name='moderatorLogout'), 
        path('<str:roomName>/roomLogout/', views.roomLogout, name='roomLogout'), 
        path('<str:roomName>/editGuestRights/', views.editGuestRights.as_view(), name='editGuestRights'),
        path('<str:roomName>/<int:noteId>/like/', views.addLike, name='like'),
        path('<str:roomName>/<int:noteId>/reply/', views.reply.as_view(), name='reply'),
        path('<str:roomName>/<int:noteId>/remove/', views.removeNote, name='removeNote'),
        path('<str:roomName>/<int:noteId>/editNote/', views.editNote.as_view(), name='editNote'),
        path('<str:roomName>/<int:noteId>/images/', views.images, name='editNote'),
        path('<str:roomName>/<int:noteId>/<int:replyId>/editReply/', views.editReply.as_view(), name='editReply'),
        path('<str:roomName>/<int:noteId>/<int:replyId>/remove/', views.removeReply, name='removeReply'),
        path('<str:roomName>/session/<str:key>/<str:val>/', views.sessionChange, name='session'),
        path('<str:roomName>/addnote/', views.addNote.as_view(), name='addnote'),
]

wall/forms.py
from django import forms
from django.utils.translation import gettext

class addNoteForm(forms.Form):
    name = forms.CharField(label=gettext("name"), max_length=50)
    storeName = forms.BooleanField(required=False, label=" Store Name")
    images = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))
    noteText = forms.CharField(required=False, max_length=2000)

class addReplyForm(forms.Form):
    name = forms.CharField(label=gettext("name"), max_length=50)
    storeName = forms.BooleanField(required=False, label=" Store Name")
    replyText = forms.CharField(required=False,max_length=2000)

class editNoteForm(addNoteForm):
    removeImages = forms.BooleanField(required=False, label=" Remove Images")

class deleteRoomForm(forms.Form):
    password = forms.CharField(required=False,max_length=32, widget=forms.PasswordInput) 

class addChangePasswordForm(forms.Form):
    oldpassword = forms.CharField(required=False,max_length=32, widget=forms.PasswordInput)
    newpassword = forms.CharField(required=False,max_length=32, widget=forms.PasswordInput)
    newpasswordrep = forms.CharField(required=False,max_length=32, widget=forms.PasswordInput)

class removePasswordForm(deleteRoomForm):
    pass

class moderatorLoginForm(deleteRoomForm):
    pass
class roomPasswordForm(deleteRoomForm):
    pass

class editGuestRightsForm(forms.Form):
    customGuestRights = forms.BooleanField(required = False)
    guestRightAddNote = forms.BooleanField(required = False)
    guestRightLikeNote = forms.BooleanField(required = False)
    guestRightAddImg = forms.BooleanField(required = False)
    guestRightAddReply = forms.BooleanField(required = False)
    guestRightEditNote = forms.BooleanField(required = False)
    guestRightEditReply = forms.BooleanField(required = False)
    guestRightRemoveNote = forms.BooleanField(required = False)
    guestRightRemoveReply = forms.BooleanField(required = False)
    guestRightChangeGuestRights = forms.BooleanField(required = False)
    guestRightAddPassword = forms.BooleanField(required = False)
    guestRightChangePassword = forms.BooleanField(required = False)
    guestRightRemovePassword = forms.BooleanField(required = False)
    guestRightChangeModeratorPassword = forms.BooleanField(required = False)
    guestRightDeleteRoom = forms.BooleanField(required = False)
    changePassword = forms.BooleanField(required = False)
    
    modPassword = forms.CharField(required=False,max_length=32, widget=forms.PasswordInput)
    oldModPassword = forms.CharField(required=False,max_length=32, widget=forms.PasswordInput)
    newModPassword = forms.CharField(required=False,max_length=32, widget=forms.PasswordInput)
    newModPasswordRep = forms.CharField(required=False,max_length=32, widget=forms.PasswordInput)

wall/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy, gettext
from django.utils import translation
from django.views import View
from django.views.generic.edit import FormView
from django.conf import settings

from django.contrib.auth.hashers import check_password, make_password

from django.http import HttpResponse, HttpResponseRedirect

from .models import Room, Note, Reply
from .forms import *

import json
import datetime as dt
from os import urandom
import os
from stickies.settings import BASE_DIR
from PIL import Image

# Create your views here.

def room(request, roomName):
    try:
        room = Room.objects.get(roomName=roomName)
    except Room.DoesNotExist:
        room = Room(roomName=roomName,
                pubDate=timezone.now(),
                lastModified=timezone.now(),
                passwordProtection = False,
                password = "",
                customGuestRights = False,
                modPassword = "",
                )
        room.save()
    
    if "password" in request.POST.keys():
        if not request.session.session_key:
            request.session.save()
        form = roomPasswordForm(request.POST)
        if form.is_valid():
            if check_password(form.cleaned_data["password"], room.password):
                if room.authorizedusers_set.filter(sessionKey = request.session.session_key).count() == 0:
                    room.authorizedusers_set.create(sessionKey = request.session.session_key,
                                                    expireDate = timezone.now() + dt.timedelta(days=14),
                                                    lastActive = timezone.now())
                elif room.authorizedusers_set.filter(sessionKey = request.session.session_key).count() == 1:
                    user = room.authorizedusers_set.filter(sessionKey = request.session.session_key)[0]
                    user.lastActive = timezone.now()
                    user.save()
            else:
                return render(request, 'wall/passwordProtectedRoom.html', {"roomName": roomName, "wrongPassword": True})
        else:
            return HttpResponseRedirect("/")
    
    # Check if room is password protected, and if user is allowed to access room
    if checkPasswordProtection(request, get_object_or_404(Room,roomName=roomName)): return render(request, 'wall/passwordProtectedRoom.html', {"roomName": roomName, "wrongPassword": False})


    # get Session Data
    try:
        ncols = request.session["ncols"]
    except KeyError:
        request.session["ncols"] = "auto"
        ncols = request.session["ncols"]
    try:
        sorting = request.session["sorting"]
    except KeyError:
        request.session["sorting"] = "mixed"
        sorting = request.session["sorting"]
    try:
        storeName = request.session["storeName"]
    except KeyError:
        request.session["storeName"] = False
        storeName = request.session["storeName"]
    try:
        username = request.session["username"]
    except KeyError:
        request.session["username"] = "anonymous"
        username = request.session["username"]



    # Handle sorting
    if sorting == "mixed":
        notes1 = room.note_set.filter(pubDate__gte=(timezone.now()- dt.timedelta(minutes=5))).order_by("-pubDate")
        notes2 = room.note_set.filter(pubDate__lt=(timezone.now()- dt.timedelta(minutes=5))).order_by("-likescommentscount")
        
        notes = [note.toDict() for note in notes1] + [note.toDict() for note in notes2]
        #notes = room.note_set.all()

    elif sorting == "agenewestfirst":
        notes = room.note_set.order_by("-pubDate")
        notes = [note.toDict() for note in notes]
    elif sorting == "ageoldestfirst":
        notes = room.note_set.order_by("pubDate")
        notes = [note.toDict() for note in notes]
    elif sorting == "likesmorefirst":
        notes = room.note_set.order_by("-likes")
        notes = [note.toDict() for note in notes]
    elif sorting == "likeslessfirst":
        notes = room.note_set.order_by("likes")
        notes = [note.toDict() for note in notes]
    elif sorting == "commentsmorefirst":
        notes = room.note_set.order_by("-commentscount")
        notes = [note.toDict() for note in notes]
    elif sorting == "commentlessfirst":
        notes = room.note_set.order_by("commentscount")
        notes = [note.toDict() for note in notes]
    else:        
        notes = room.note_set.all()
        notes = [note.toDict() for note in notes]
    
    for i in range(0, len(notes)):
        note = get_object_or_404(Note, pk=notes[i]["id"])
        replies = note.reply_set.order_by("pubDate")
        replies = [reply.toDict() for reply in replies]
        notes[i]["replies"] = replies
    for i in range(0,len(notes)):
        note = get_object_or_404(Note, pk=notes[i]["id"])
        imgs = note.imagefile_set.all()
        imgs = [{"id": img.id, "file": str(img.file)} for img in imgs]
        notes[i]["imgs"] = imgs


    
    context = { "roomName": roomName,
                "roomType": "wall",
                "passwordProtection" : room.passwordProtection,
                "customGuestRights": room.customGuestRights,
                #"notes": mark_safe(json.dumps(notes).replace("\'","\\\'")),
                "notes": mark_safe(json.dumps(notes)),
                "ncols": ncols,
                "sorting": sorting,
                "lastModified": room.lastModified.timestamp(),
              }
    if room.customGuestRights:
        context["guestRightsJS"] = mark_safe(json.dumps(room.customguestrights_set.all()[0].toDict()).replace("True", "true").replace("False","false"))
        context["guestRights"] = room.customguestrights_set.all()[0]
        if (room.authorizedmoderators_set.filter(sessionKey=request.session.session_key).count() == 1
            and room.authorizedmoderators_set.filter(sessionKey=request.session.session_key)[0].expireDate > timezone.now()
            and timezone.now() - room.authorizedmoderators_set.filter(sessionKey=request.session.session_key)[0].lastActive < dt.timedelta(minutes=10)):
            context["isMod"] = True
    return render(request, 'wall/wall.html', context)
    #return HttpResponse("Welcome to room " + roomName)

def sessionChange(request,roomName,key,val):
    # Check if room is password protected, and if user is allowed to access room
    if checkPasswordProtection(request, get_object_or_404(Room,roomName=roomName)): return render(request, 'wall/passwordProtectedRoom.html', {"roomName": roomName, "wrongPassword": False})
    
    request.session[key] = val
    if key == "django_language":
        request.session['language_id'] = val
        #gettext.textdomain(val)
        #translation.activate(val)
        #translation.override(val)
        #response = HttpResponseRedirect("/wall/" + roomName)
        #response.set_cookie(settings.LANGUAGE_COOKIE_NAME, val)
        #import logging
        #logging.critical(str(key) for key in request.session.keys())
        #logging.critical(request.session["django_language"])
    return HttpResponseRedirect("/wall/" + roomName)

def checkUpdate(request, roomName):
    # Check if room is password protected, and if user is allowed to access room
    if checkPasswordProtection(request, get_object_or_404(Room,roomName=roomName)): return HttpResponse(json.dumps({"msg": "passwordRequired"}))

    room = get_object_or_404(Room, roomName=roomName)

    if (room.passwordProtection and request.session.session_key and room.authorizedusers_set.filter(sessionKey=request.session.session_key).count() == 1):
        user = room.authorizedusers_set.filter(sessionKey = request.session.session_key)[0]
        user.lastActive = timezone.now()
        user.save()
    if (room.customGuestRights and request.session.session_key and room.authorizedmoderators_set.filter(sessionKey=request.session.session_key).count() == 1):
        user = room.authorizedmoderators_set.filter(sessionKey = request.session.session_key)[0]
        user.lastActive = timezone.now()
        user.save()
        
    context = { "roomName": roomName,
                "passwordProtection": room.passwordProtection,
                "lastModified": room.lastModified.timestamp(),
              }
    return HttpResponse(json.dumps(context))

def update(request, roomName):
    # Check if room is password protected, and if user is allowed to access room
    if checkPasswordProtection(request, get_object_or_404(Room,roomName=roomName)): return render(request, 'wall/passwordProtectedRoom.html', {"roomName": roomName, "wrongPassword": False})

    room = get_object_or_404(Room, roomName=roomName)
        
    try:
        sorting = request.session["sorting"]
    except KeyError:
        request.session["sorting"] = "mixed"
        sorting = request.session["sorting"]
    # Handle sorting
    if sorting == "mixed":
        notes1 = room.note_set.filter(pubDate__gte=(timezone.now()- dt.timedelta(minutes=5))).order_by("-pubDate")
        notes2 = room.note_set.filter(pubDate__lt=(timezone.now()- dt.timedelta(minutes=5))).order_by("-likescommentscount")
        
        notes = [note.toDict() for note in notes1] + [note.toDict() for note in notes2]
        #notes = room.note_set.all()

    elif sorting == "agenewestfirst":
        notes = room.note_set.order_by("-pubDate")
        notes = [note.toDict() for note in notes]
    elif sorting == "ageoldestfirst":
        notes = room.note_set.order_by("pubDate")
        notes = [note.toDict() for note in notes]
    elif sorting == "likesmorefirst":
        notes = room.note_set.order_by("-likes")
        notes = [note.toDict() for note in notes]
    elif sorting == "likeslessfirst":
        notes = room.note_set.order_by("likes")
        notes = [note.toDict() for note in notes]
    elif sorting == "commentsmorefirst":

wall/templates/wall/addChangePasswordForm.html
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
{% load static %}
{% load i18n %}

<!-- {{request.session.django_language}} -->
{% language request.session.django_language %}

<html>
  <head>
    <meta charset="utf-8">
    <title>Stickies!</title>
		<link rel="stylesheet" type="text/css" href="{% static 'wall/addChangePassword.css' %}">
  </head>
  <body>
      <!--<div class="header">
				<h1>
					{% if passwordProtection %}
  					{% translate 'Change password of room ' %}{{roomName}}
					{% else %}
  					{% translate 'Add password to room ' %}{{roomName}}
					{% endif %}
				</h1>
			</div>-->
			{% include "general/header/header-simple.html" %}
			<center>
  			<div class="main">
					<p>
					{{msg}}
						<br>
						{% if errormsg %}
						<p style="color: red;">{{errormsg}}</p>
						{% endif %}
						<form action="/wall/{{roomName}}/addChangePassword/" id="addChangePasswordForm" method="POST">
							{% csrf_token %}
							{% if wrongPassword %}
							  <p style="color: red;">{% translate "Error: password didn't match" %}</p>
							{% endif %}

							{% if passwordProtection %}
						  <label for="oldpassword">{% translate "Old password: " %}</label>
   						<input type="text" id="oldpassword" name="oldpassword" maxlength=100>
	   					<br>
							{% endif %}
						  <label for="newpassword">{% translate "New password: " %}</label>
   						<input type="text" id="newpassword" name="newpassword" maxlength=100>
	   					<br>
						  <label for="newpasswordre">{% translate "Repeat password: " %}</label>
   						<input type="text" id="newpasswordrep" name="newpasswordrep" maxlength=100>
	   					<br>
							<button type="button" id="generatePassword" name="generatePassword" class="inputPassword" onclick="getGeneratedPassword(this)">{% translate "Generate password" %}</button>
							<br>
							<button type="button" class="cancel"><a href="/wall/{{roomName}}/">{%translate 'Cancel' %}</a></button>
							<input type="button" onclick="checkForm()" value="{% if passwordProtection %} {% translate 'Change password' %} {% else %} {% translate 'Add password' %} {% endif %}">
						</form>
			    </p>
			  </div>
		  </center>
		
  </body>
	<script>
		function getGeneratedPassword(e) {
      let pw;
      const http = new XMLHttpRequest();
      http.open("GET","/generatePassword/");
      http.send();
      http.onreadystatechange = function () {
        if (this.readyState == 4 && this.status == 200) {
          pw = http.responseText;
          console.log(pw);
          document.getElementById("newpassword").value = pw;
          document.getElementById("newpasswordrep").value = pw;
        }
      }
    }
		function checkForm() {
		  if (document.getElementById("newpassword").value == "" && document.getElementById("newpasswordrep").value == "") {
		    if (confirm ('{% translate "You left an empty password. Are you sure, you want to leave the password empty?" %}')) {document.getElementById("addChangePasswordForm").submit();}
			
			}
			else {document.getElementById("addChangePasswordForm").submit();}
		}
	</script>

</html>

{% endlanguage %}

wall/templates/wall/editGuestRights.html
<!DOCTYPE html>

 <meta name="viewport" content="width=device-width, initial-scale=1.0">

{% load static %}
{% load i18n %}

<!-- uncomment (replace # with % to test translations) -->
<!-- don't forget {# endlanguage # } at bottom -->

{% language request.session.django_language %}
<!-- {{ request.session.django_language }} -->
{# get_current_language as LANGUAGE_CODE #}

<html>
  <head>
    <meta charset="utf-8">
    <title>Stickies!</title>
		<link rel="stylesheet" type="text/css" href="{% static 'startapp/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'startapp/menu.css' %}">
  </head>
  <body>
      <!--<div class="header">
          <h1 class="heading">Stickies!</h1>
      </div>
			-->
			{% include "general/header/header-simple.html" %}
		<div class="vcenter">
			<div class="main">
                <h2> {% translate "Manage guest rights" %}</h2>
				<!--<p>This is my page</p>-->
				<form action="{% url 'wall:editGuestRights' roomName%}" method="post" id="changeGuestRightsForm">
					<fieldset>
						{% csrf_token %}
						<input type="checkbox" name="customGuestRights" id="customGuestRights" checked>
						<label for="customGuestRights">{%translate "Customize guest rights" %}</label>
						<br>
						<br>
						<br>
						<div name="divCustomGuestRights" id="divCustomGuestRights">
							<input type="checkbox" name="guestRightAddNote" id="guestRightAddNote" {% if not guestRights or guestRights.addNote %}checked{%endif%}>
							<label for="guestRightAddNote">{% translate "Add notes" %}</label>
							<br>
							<input type="checkbox" name="guestRightLikeNote" id="guestRightLikeNote" {% if not guestRights or guestRights.likeNote %}checked{%endif%}>
							<label for="guestRightLikeNote">{% translate "Like notes" %}</label>
							<br>
							<input type="checkbox" name="guestRightAddImg" id="guestRightAddImg" {% if not guestRights or guestRights.addImg %}checked{%endif%}>
							<label for="guestRightAddImg">{% translate "Add images" %}</label>
							<br>
							<input type="checkbox" name="guestRightAddReply" id="guestRightAddReply" {% if not guestRights or guestRights.addReply %}checked{%endif%}>
							<label for="guestRightAddReply">{% translate "Add replies" %}</label>
							<br>
							<input type="checkbox" name="guestRightEditNote" id="guestRightEditNote" {% if not guestRights or guestRights.editNote %}checked{%endif%}>
							<label for="guestRightEditNote">{% translate "Edit notes" %}</label>
							<br>
							<input type="checkbox" name="guestRightEditReply" id="guestRightEditReply" {% if not guestRights or guestRights.editReply %}checked{%endif%}>
							<label for="guestRightEditReply">{% translate "Edit replies" %}</label>
							<br>
							<input type="checkbox" name="guestRightRemoveNote" id="guestRightRemoveNote" {% if not guestRights or guestRights.removeNote %}checked{%endif%}>
							<label for="guestRightRemoveNote">{% translate "Remove notes" %}</label>
							<br>
							<input type="checkbox" name="guestRightRemoveReply" id="guestRightRemoveReply" {% if not guestRights or guestRights.removeReply %}checked{%endif%}>
							<label for="guestRightRemoveReply">{% translate "Remove replies" %}</label>
							<br>
							<input type="checkbox" name="guestRightChangeGuestRights" id="guestRightChangeGuestRight"{% if guestRights and guestRights.changeGuestRights %}checked{%endif%}>
							<label for="guestRightChangeGuestRights">{% translate "Change guest rights" %}</label>
							<br>
							<input type="checkbox" name="guestRightAddPassword" id="guestRightAddPasword"{% if guestRights and guestRights.addPassword %}checked{%endif%}>
							<label for="guestRightAddPasword">{% translate "Add pasword to room" %}</label>
							<br>
							<input type="checkbox" name="guestRightRemovePassword" id="guestRightRemovePasword"{% if guestRights and guestRights.removePassword %}checked{%endif%}>
							<label for="guestRightRemovePasword">{% translate "Remove password from room" %}</label>
							<br>
							<input type="checkbox" name="guestRightChangePassword" id="guestRightChangePassword"{% if guestRights and guestRights.changePassword %}checked{%endif%}>
							<label for="guestRightChangePassword">{% translate "Change password of room" %}</label>
							<br>
							<input type="checkbox" name="guestRightChangeModeratorPassword" id="guestRightChangeModeratorPassword"{% if guestRights and guestRights.changeModeratorPassword %}checked{%endif%}>
							<label for="guestRightChangeModeratorPassword">{% translate "Change moderator password" %}</label>
							<br>
							<input type="checkbox" name="guestRightDeleteRoom" id="guestRightDeleteRoom"{% if guestRights and guestRights.deleteRoom %}checked{%endif%}>
							<label for="guestRightDeleteRoom">{% translate "Delete room" %}</label>
							<br>
					    
							{% if not customGuestRights %}
							<div class="divPasswordStuff">
			        <br>
							<label for="modPassword" id="labelModPassword">{% translate "Moderator password: " %}</label>
							<br>
							<input type="text" id="modPassword" name="modPassword" style="max-width: 90%; min-width: 250px;"><br>
							<button type="button" id="modGeneratePassword" name="modGeneratePassword" onclick="getGeneratedPassword('modPassword')">{% translate "generate" %}</button>
							</div>
							{% elif customGuestRights or errmsg %}
							<br>
							<input type="checkbox" name="changePassword" id="changePassword" onchange='toggleChangePassword()' {% if errmsg %} checked {% endif %}>
							<label for="guestRightDeleteRoom">{% translate "Change Password" %}</label>
							{% if errmsg %}<p style="color:red;">{{errmsg}}</p>{%endif%}
							<div class="divPasswordStuff" id="divPasswordStuff" style="display:none;">
			        <br>
							<label for="oldModPassword" id="labelOldModPassword">{% translate "Old moderator password: " %}</label>
							<br>
							<input type="text" id="oldModPassword" name="oldModPassword" style="max-width: 90%; min-width: 250px;" maxlength=100><br>
							<label for="newModPassword" id="labelNewModPassword">{% translate "New moderator password: " %}</label>
							<br>
							<input type="text" id="newModPassword" name="newModPassword" style="max-width: 90%; min-width: 250px;" maxlength=100><br>
							<label for="newModPasswordRep" id="labelNewModPasswordRep">{% translate "Repeat new moderator password: " %}</label>
							<br>
							<input type="text" id="newModPasswordRep" name="newModPasswordRep" style="max-width: 90%; min-width: 250px;" maxlength=100><br>
							<button type="button" id="modGeneratePassword" name="modGeneratePassword" onclick="getGeneratedPassword('modPassword')">{% translate "generate" %}</button>
							</div>
							{% endif %}
						</div>
						<br>

  					<input class="buttonSubmit" type="button" onclick="checkForm()" value={% translate "Edit!" %}>
					</fieldset>
				</form>

			</div>
		</div>
  </body>
	<script>
		function getGeneratedPassword(id) {
			let pw;
			const http = new XMLHttpRequest();
	    http.open("GET","/generatePassword/");
			http.send();
			http.onreadystatechange = function () {
				if (this.readyState == 4 && this.status == 200) {
					pw = http.responseText;
					console.log(pw);
					{% if customGuestRights or errmgs %}
			    document.getElementById("newModPassword").value = pw;
			    document.getElementById("newModPasswordRep").value = pw;
					{% else %}
			    document.getElementById(id).value = pw;
					{%endif %}
				}
			}
	  }
		{% if customGuestRights %}
		function toggleChangePassword() {
			chkbx = document.getElementById("changePassword");
			if (chkbx.checked) {document.getElementById("divPasswordStuff").style.display = "inline"}
			else {document.getElementById("divPasswordStuff").style.display = "none"}
		}
		toggleChangePassword();
		{% endif %}
		function checkForm() {		
			 if ((document.getElementById("newModPassword") != null && document.getElementById("changePassword").checked && document.getElementById("newModPassword").value == "" && document.getElementById("newModPasswordRep").value == "") || (document.getElementById("modPassword") != null && document.getElementById("modPassword").value == "")) {
		     if (confirm ('{% translate "You left an empty password. Are you sure, you want to leave the password empty?" %}')) {document.getElementById("changeGuestRightsForm").submit();}

			}
			else {document.getElementById("changeGuestRightsForm").submit();}

		}
	</script>
</html>


{% endlanguage %}

wall/templates/wall/error.html
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
{% load static %}
{% load i18n %}

<!-- {{request.session.django_language}} -->
{% language request.session.django_language %}

<html>
  <head>
    <meta charset="utf-8">
    <title>Stickies!</title>
		<link rel="stylesheet" type="text/css" href="{% static 'wall/passwordProtectedRoom.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'wall/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'wall/addEditContentForm.css' %}">
  </head>
  <body>
      <div class="header">
				<h1> {{ strTitle }}</h1>
      </div>
			<center>
  			<div class="main">
					{% if noteText %}
					<div class="note origNote">{{noteText}}</div>
					{% endif %}
					<p>
					{{ message }}
			    </p>
					{% if buttonCancel %}
					<button><a href={{buttonCancelLink}}>{{buttonCancelText}}</a></button>
					{% endif %}
					<button><a href={{buttonLink}}>{{ buttonText }}</a></button>
			  </div>
		  </center>
		
  </body>
</html>

{% endlanguage %}

wall/templates/wall/images.html
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
{% load static %}
{% load i18n %}

<!-- {{request.session.django_language}} -->
{% language request.session.django_language %}

<html>
  <head>
    <meta charset="utf-8">
    <title>Stickies!</title>
		<link rel="stylesheet" type="text/css" href="{% static 'wall/passwordProtectedRoom.css' %}">
  </head>
  <body>
      <div class="header">
				<h1>Stickies</h1>
      </div>
			<center>
				<a href="/wall/{{roomName}}/">
					<button style="width:20%; height:50px; margin-bottom:20px; margin-top:20px">{% translate "Back" %}</button>
				</a>
  			<div class="main">
				  {% for img in imgs %}

					<a href="/media/{{img.file}}" target="_blank">
					  <img src="/media/{{img.file}}" style="width:100%;margin-bottom:2%"></a>

					{% endfor%}
			  </div>
				<br>
				<a href="/wall/{{roomName}}/">
					<button style="width:20%; height:50px;">{% translate "Back" %}</button>
				</a>
				<br>
		  </center>
		
  </body>
</html>

{% endlanguage %}