startapp/urls.py
from django.urls import path

from . import views

app_name= "startapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('lang/<str:lang>/', views.setLang, name='setLang'),
    path('lang/<str:lang>/<path:path>/', views.setLang, name='setLang'),
    #path('lang/<str:lang>/<str:info>/<str:infoType>/', views.setLang, name='setLang'),
    #path('lang/<str:lang>/<str:info>/<str:infoType>/<str:roomType>/<str:roomName>/', views.setLang, name='setLang'),
    path('generatePassword/', views.generatePassword, name="generatePassword"),
    path('create/', views.create, name="create"),
    path('info/<str:infotype>/', views.info, name="info"),
    path('info/<str:infotype>/<str:roomType>/<str:roomName>/', views.info, name="info"),
]

stickies/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns # make static files work with gunicorn

urlpatterns = [
    path('', include('startapp.urls')),
    path('wall/', include('wall.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns() # make static files work with gunicorn

#test with media files
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from django.conf import settings

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

wall/urls.py
from django.urls import path

from . import views

app_name= "wall"

urlpatterns = [
        path('<str:roomName>/', views.room, name='index'),
        path('<str:roomName>/error/<str:errorType>/', views.error, name='error'),
        path('<str:roomName>/addChangePassword/', views.addChangePassword.as_view(), name='addChangePassword'),
        path('<str:roomName>/removePassword/', views.removePassword.as_view(), name='removePassword'),
        path('<str:roomName>/checkUpdate/', views.checkUpdate, name='checkUpdate'),
        path('<str:roomName>/update/', views.update, name='update'),
        path('<str:roomName>/delete/', views.delete.as_view(), name='delete'),
        path('<str:roomName>/moderatorLogin/', views.moderatorLogin.as_view(), name='moderatorLogin'),
        path('<str:roomName>/moderatorLogout/', views.moderatorLogout, name='moderatorLogout'), 
        path('<str:roomName>/roomLogout/', views.roomLogout, name='roomLogout'), 
        path('<str:roomName>/editGuestRights/', views.editGuestRights.as_view(), name='editGuestRights'),
        path('<str:roomName>/<int:noteId>/like/', views.addLike, name='like'),
        path('<str:roomName>/<int:noteId>/reply/', views.reply.as_view(), name='reply'),
        path('<str:roomName>/<int:noteId>/remove/', views.removeNote, name='removeNote'),
        path('<str:roomName>/<int:noteId>/editNote/', views.editNote.as_view(), name='editNote'),
        path('<str:roomName>/<int:noteId>/images/', views.images, name='editNote'),
        path('<str:roomName>/<int:noteId>/<int:replyId>/editReply/', views.editReply.as_view(), name='editReply'),
        path('<str:roomName>/<int:noteId>/<int:replyId>/remove/', views.removeReply, name='removeReply'),
        path('<str:roomName>/session/<str:key>/<str:val>/', views.sessionChange, name='session'),
        path('<str:roomName>/addnote/', views.addNote.as_view(), name='addnote'),
]

startapp/models.py
from django.db import models

# Create your models here.

startapp/forms.py
from django import forms
from django.utils.translation import gettext

class createRoomForm(forms.Form):
    roomName = forms.CharField(max_length=100)
    roomType = forms.CharField(max_length=30)

    customGuestRights = forms.BooleanField(required = False)
    guestRightAddNote = forms.BooleanField(required = False)
    guestRightLikeNote = forms.BooleanField(required = False)
    guestRightAddImg = forms.BooleanField(required = False)
    guestRightAddReply = forms.BooleanField(required = False)
    guestRightEditNote = forms.BooleanField(required = False)
    guestRightEditReply = forms.BooleanField(required = False)
    guestRightRemoveNote = forms.BooleanField(required = False)
    guestRightRemoveReply = forms.BooleanField(required = False)
    guestRightChangeGuestRights = forms.BooleanField(required = False)
    guestRightAddPassword = forms.BooleanField(required = False)
    guestRightChangePassword = forms.BooleanField(required = False)
    guestRightRemovePassword = forms.BooleanField(required = False)
    guestRightChangeModeratorPassword = forms.BooleanField(required = False)
    guestRightDeleteRoom = forms.BooleanField(required = False)
    changePassword = forms.BooleanField(required = False)
    
    modPassword = forms.CharField(required=False,max_length=100, widget=forms.PasswordInput)

    passwordProtection = forms.BooleanField(required=False)
    password = forms.CharField(required=False, max_length=100, widget=forms.PasswordInput)

startapp/views.py
from django.shortcuts import render
from django.utils import translation
from django.utils import timezone
from django.utils.translation import gettext
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.hashers import check_password, make_password
import datetime
from os import urandom
# Create your views here.

#from wall.models import Room as WallRoom
from wall.models import Room

from .forms import *

def index(request):
    return render(request, 'startapp/index.html')
def create(request):
    form = createRoomForm(request.POST)

    if form.is_valid():
        roomName = form.cleaned_data["roomName"]
        roomType = form.cleaned_data["roomType"]
        if not request.session.session_key:
            request.session.save()

        if (Room.objects.filter(roomName=form.cleaned_data["roomName"]).count() == 0 
                and (form.cleaned_data["passwordProtection"] or form.cleaned_data["customGuestRights"])):
            #pw = make_password(request.POST["password"], salt=urandom(25).hex())
            #modpw = make_password(request.POST["modPassword"], salt=urandom(25).hex())
            room = Room(roomName = roomName,
                        pubDate = timezone.now(),
                        lastModified = timezone.now(),
                        passwordProtection = form.cleaned_data["passwordProtection"],
                        password=make_password(form.cleaned_data["password"], salt=urandom(25).hex()) if form.cleaned_data["passwordProtection"] else "",
                        customGuestRights = form.cleaned_data["customGuestRights"],
                        modPassword = make_password(form.cleaned_data["modPassword"], salt=urandom(25).hex()) if form.cleaned_data["customGuestRights"] else "",
                    )
            room.save()
            if form.cleaned_data["passwordProtection"]:
                room.authorizedusers_set.create(sessionKey=request.session.session_key,
                        expireDate=timezone.now() + datetime.timedelta(days=14),
                        lastActive=timezone.now())
                room.save()
            if form.cleaned_data["customGuestRights"]:
                room.authorizedmoderators_set.create(sessionKey=request.session.session_key,
                        expireDate=timezone.now() + datetime.timedelta(days=14),
                        lastActive=timezone.now())
                room.customguestrights_set.create(
                        addNote = form.cleaned_data["guestRightAddNote"],
                        likeNote = form.cleaned_data["guestRightLikeNote"],
                        addImg = form.cleaned_data["guestRightAddImg"],
                        addReply = form.cleaned_data["guestRightAddReply"],
                        editNote = form.cleaned_data["guestRightEditNote"],
                        editReply = form.cleaned_data["guestRightEditReply"],
                        removeNote = form.cleaned_data["guestRightRemoveNote"],
                        removeReply = form.cleaned_data["guestRightRemoveReply"],
                        changeGuestRights = form.cleaned_data["guestRightChangeGuestRights"],
                        addPassword = form.cleaned_data["guestRightAddPassword"],
                        removePassword = form.cleaned_data["guestRightRemovePassword"],
                        changePassword = form.cleaned_data["guestRightChangePassword"],
                        changeModeratorPassword = form.cleaned_data["guestRightChangeModeratorPassword"],
                        deleteRoom = form.cleaned_data["guestRightDeleteRoom"],       
                        )
                room.save()
        if Room.objects.filter(roomName=form.cleaned_data["roomName"]).count() == 1:
           #     and ("passwordProtection" in request.POST.keys() or "customGuestRights" in request.POST.keys())):
            room = Room.objects.filter(roomName=form.cleaned_data["roomName"])[0]
            if form.cleaned_data["passwordProtection"] and room.passwordProtection and check_password(form.cleaned_data["password"], room.password):
                if room.authorizedusers_set.filter(sessionKey=request.session.session_key).count() == 0:
                    room.authorizedusers_set.create(sessionKey=request.session.session_key,
                            expireDate=timezone.now() + datetime.timedelta(days=14),
                            lastActive=timezone.now())
                elif room.authorizedusers_set.filter(sessionKey=request.session.session_key).count() == 1:
                    user = room.authorizedusers_set.filter(sessionKey=request.session.session_key)[0]
                    user.lastActive=timezone.now()
                    user.save()
                else: 
                    return 0
            if form.cleaned_data["customGuestRights"] and room.customGuestRights and check_password(form.cleaned_data["modPassword"], room.modPassword):
                if room.authorizedmoderators_set.filter(sessionKey=request.session.session_key).count() == 0:
                        room.authorizedmoderators_set.create(sessionKey=request.session.session_key,
                                expireDate=timezone.now() + datetime.timedelta(days=14),
                                lastActive=timezone.now())
                elif room.authorizedmoderators_set.filter(sessionKey=request.session.session_key).count() == 1:
                    user = room.authorizedmoderators_set.filter(sessionKey=request.session.session_key)[0]
                    user.lastActive = timezone.now()
                    user.save()
                else: return 0

            if ((form.cleaned_data["passwordProtection"] and not check_password(form.cleaned_data["password"], room.password))
                    or (form.cleaned_data["customGuestRights"] and not check_password(form.cleaned_data["modPassword"], room.modPassword))):
                        
                context = {"roomName": form.cleaned_data["roomName"],
                           "roomType": form.cleaned_data["roomType"],
                           "strTitle": gettext("Room %(roomName)s already exists") % {"roomName": form.cleaned_data["roomName"]},
                           "buttonText":  gettext("Join room"),
                           }

                context["msg"] = gettext("This room already exists with the following conditions:")
                context["msglist"] = []

                if room.passwordProtection:
                    context["msglist"] += [gettext("Password protection")]
                else:
                    context["msglist"] += [gettext("NO (!) password protection")]
                if room.customGuestRights:
                    context["msglist"] += [gettext("customized Guest Rights")]
                else:
                    context["msglist"] += [gettext("NO (!) Guest Rights")]

                context["aftermsglist"] = gettext("If you created the room, and know the relevant passwords, go ahead. Otherwise go back and create a new room, with a different room name.")


                return render(request, 'wall/roomAlreadyExists.html', context)

        # for a normal room, just go ahead
        return HttpResponseRedirect('/' + roomType + '/' + roomName)
    else:
        return HttpResponseRedirect('/')

def info(request, infotype, roomType=None, roomName=None):
    context = {}
    if type(roomType) != type(None):
        context["roomType"] = roomType
    if type(roomName) != type(None):
        context["roomName"] = roomName
    context["info"] = True
    context["infoType"] = infotype
    return render(request, "general/" + infotype + ".html", context)
    
#def setLang(request, lang, info=None, infoType=None, roomType=None, roomName=None):
def setLang(request, lang, path=None):
    response = HttpResponseRedirect('/')
    #translation.activate(lang)
    #response.set_cookie("django_language", lang)
    request.session["django_language"] = lang
    """URL = "/"
    if type(info) != type(None):
        URL += "info/"
    if type(infoType) != type(None):
        URL += infoType + "/"
    if type(roomType) != type(None):
        URL += roomType + "/"
    if type(roomName) != type(None):
        URL += roomName + "/" """

    return HttpResponseRedirect("/" + path if type(path) != type(None) else "/")

def generatePassword(request):
    return HttpResponse(urandom(15).hex())

startapp/templates/startapp/index.html
<!DOCTYPE html>

 <meta name="viewport" content="width=device-width, initial-scale=1.0">

{% load static %}
{% load i18n %}

<!-- uncomment (replace # with % to test translations) -->
<!-- don't forget {# endlanguage # } at bottom -->

{% language request.session.django_language %}
<!-- {{ request.session.django_language }} -->
{# get_current_language as LANGUAGE_CODE #}

<html>
  <head>
    <meta charset="utf-8">
    <title>Stickies!</title>
		<link rel="stylesheet" type="text/css" href="{% static 'startapp/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'startapp/menu.css' %}">
  </head>
  <body>
		{% include "general/header/header-simple.html" %}
		<div class="vcenter">
			<div class="main">
                <h2> {% translate "Create your room to collaborate!" %}</h2>
				<!--<p>This is my page</p>-->

				<form action="{% url 'startapp:create' %}" method="post" id="roomCreationForm">
					<fieldset>
						{% csrf_token %}
						
						<label for="roomName">{% translate "Room name" %}</label>
            <input type="text" id="roomName" name="roomName" maxlength=100> <br>

						<label for=rommType">{% translate "Room type" %}</label>
						<select name="roomType">
							<option value="wall"> {% translate "Bulletin board" %}</option>
              <option value="test">Test (not working)</option>
						</select>
						<br>

						<input type="checkbox" name="customGuestRights" id="customGuestRights" onchange="toggleCustomGuestRights(this)">
						<label for="customGuestRights">{%translate "Customize guest rights" %}</label>
						<br>
						<div name="divCustomGuestRights" id="divCustomGuestRights" class="divCustomGuestRights">
							<input type="checkbox" name="guestRightAddNote" id="guestRightAddNote" checked>
							<label for="guestRightAddNote">{% translate "Add notes" %}</label>
							<br>
							<input type="checkbox" name="guestRightLikeNote" id="guestRightLikeNote" checked>
							<label for="guestRightLikeNote">{% translate "Like notes" %}</label>
							<br>
							<input type="checkbox" name="guestRightAddImg" id="guestRightAddImg" checked>
							<label for="guestRightAddImg">{% translate "Add images" %}</label>
							<br>
							<input type="checkbox" name="guestRightAddReply" id="guestRightAddReply" checked>
							<label for="guestRightAddReply">{% translate "Add replies" %}</label>
							<br>
							<input type="checkbox" name="guestRightEditNote" id="guestRightEditNote" checked>
							<label for="guestRightEditNote">{% translate "Edit notes" %}</label>
							<br>
							<input type="checkbox" name="guestRightEditReply" id="guestRightEditReply" checked>
							<label for="guestRightEditReply">{% translate "Edit replies" %}</label>
							<br>
							<input type="checkbox" name="guestRightRemoveNote" id="guestRightRemoveNote" checked>
							<label for="guestRightRemoveNote">{% translate "Remove notes" %}</label>
							<br>
							<input type="checkbox" name="guestRightRemoveReply" id="guestRightRemoveReply" checked>
							<label for="guestRightRemoveReply">{% translate "Remove replies" %}</label>
							<br>
							<input type="checkbox" name="guestRightChangeGuestRights" id="guestRightChangeGuestRight">
							<label for="guestRightChangeGuestRights">{% translate "Change guest rights" %}</label>
							<br>
							<input type="checkbox" name="guestRightAddPassword" id="guestRightAddPasword">
							<label for="guestRightAddPasword">{% translate "Add pasword to room" %}</label>
							<br>
							<input type="checkbox" name="guestRightRemovePassword" id="guestRightRemovePasword">
							<label for="guestRightRemovePasword">{% translate "Remove password from room" %}</label>
							<br>
							<input type="checkbox" name="guestRightChangePassword" id="guestRightChangePassword">
							<label for="guestRightChangePassword">{% translate "Change password of room" %}</label>
							<br>
							<input type="checkbox" name="guestRightChangeModeratorPassword" id="guestRightChangeModeratorPassword">
							<label for="guestRightChangeModeratorPassword">{% translate "Change moderator password" %}</label>
							<br>
							<input type="checkbox" name="guestRightDeleteRoom" id="guestRightDeleteRoom">
							<label for="guestRightDeleteRoom">{% translate "Delete room" %}</label>
							<br>
						
							<div class="divPasswordStuff">
			        <br>
							<label for="modPassword" id="labelModPassword">{% translate "Moderator password: " %}</label>
							<br>
							<input type="text" id="modPassword" name="modPassword" style="max-width: 90%; min-width: 250px;" maxlength=100><br>
							<button type="button" id="modGeneratePassword" name="modGeneratePassword" onclick="getGeneratedPassword('modPassword')">{% translate "generate" %}</button>
							</div>
						</div>
						<br>

						<input type="checkbox" name="passwordProtection" id="passwordProtection" onchange="showPasswordField(this)">
						<label for="passwordProtection" >{%translate "Protect room with password" %}</label>
            <br>
						<div class="divPasswordStuff">
						<label for="password" class="inputPassword" id="labelPassword">{% translate "Password: " %}</label>
						<br>
						<input type="text" id="password" name="password" class="inputPassword" style="max-width: 90%; min-width: 250px;" maxlength=100>
						<br>
						<button type="button" id="generatePassword" name="generatePassword" class="buttonGeneratePassword" onclick="getGeneratedPassword('password')">{% translate "generate" %}</button>
						</div>
						<br><br>
  					<input class="buttonSubmit" type="button" onclick="checkForm()" value={% translate "create!" %}>
					</fieldset>
				</form>

			</div>
		</div>
  </body>
	<script>
		showPasswordField(document.getElementById("passwordProtection"));
		toggleCustomGuestRights(document.getElementById("divCustomGuestRights"))
		function showPasswordField(e) {
		  if (e.checked) {
				document.getElementById("password").style.display = "inline";
				document.getElementById("labelPassword").style.display = "inline";
				document.getElementById("generatePassword").style.display = "inline";
			}
			else {
				document.getElementById("password").style.display = "none";
				document.getElementById("labelPassword").style.display = "none";
				document.getElementById("generatePassword").style.display = "none";
			}
	  }
		function toggleCustomGuestRights(e) {
		  if (e.checked) {
				document.getElementById("divCustomGuestRights").style.display = "inline";
			}
			else {
				document.getElementById("divCustomGuestRights").style.display = "none";
			}
	  }
		function getGeneratedPassword(id) {
			let pw;
			const http = new XMLHttpRequest();
	    http.open("GET","generatePassword/");
			http.send();
			http.onreadystatechange = function () {
				if (this.readyState == 4 && this.status == 200) {
					pw = http.responseText;
					console.log(pw);
			    document.getElementById(id).value = pw;
				}
			}
	  }
		function checkForm() {
			if (document.getElementById("roomName").value == "") {alert('{% translate "Room name should not be empty" %}'); return 0;}
			else if (document.getElementById("customGuestRights").checked && document.getElementById("passwordProtection").checked && document.getElementById("password").value == "" && document.getElementById("password").value == "") {
		    if (confirm ('{% translate "You have selected password protection and customized guest rights, but left both an password. Are you sure, you want to leave the passwords empty?" %}')) {document.getElementById("roomCreationForm").submit();}
			}
		  else if (document.getElementById("passwordProtection").checked && document.getElementById("password").value == "") {
		    if (confirm ('{% translate "You have selected password protection but left an empty password. Are you sure, you want to leave the password empty?" %}')) {document.getElementById("roomCreationForm").submit();}
			}
		  else if (document.getElementById("customGuestRights").checked && document.getElementById("modPassword").value == "") {
		    if (confirm ('{% translate "You have selected customized guest rights, but left an empty moderator password. Are you sure, you want to leave the password empty?" %}')) {document.getElementById("roomCreationForm").submit();}
			}
			
			else {document.getElementById("roomCreationForm").submit();}
		}
	</script>

	{% include "general/footer.html" %}
	<script>
		let hiddendiv = document.getElementById("hiddendiv");
		let footer = document.getElementById("footer");
		footer.style.position = "fixed";
		footer.style.bottom = "0px";
		footer.style.display = "block";
		footer.style.marginBottom="10px"
		hiddendiv.style.display = "block";
	</script>
</html>


{% endlanguage %}